---
- name: Create a security group and provision a linux instance
  hosts: localhost
  connection: local
  vars:
    webserver_key_name: "<key_name>"
  roles:
    - role: "./roles/infra-setup"

- name: Create the webserver and configure the apache service
  hosts: webserver_ec2
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "./keys/secret_<key_name>.pem"
  roles:
    - role: "./roles/webserver"